### ISSUE TITLE
头像的BUG

### ISSUE THREAD

**Issue by Jude95** [haruue/bihu#2]
点选择。失败。
点保存。崩溃。
所有圆型头像都有锯齿。建议用Glide。
抽屉的Header加个背景图吧。

**Comment by haruue** [comment]
- 圆形头像锯齿貌似是 [CircleImageView](https://github.com/haruue/bihu/blob/master/app/src/main/java/cn/com/caoyue/bihu/ui/widget/CircleImageVIew.java) 的锅。。。
- 头像选择失败是那时候发现不同安卓版本**甚至是不同品牌手机**选择的方式都不一样，依赖相册来选将会很复杂，由于当时仅仅是测试所以就直接把包名写死了。。。https://github.com/haruue/bihu/commit/463861adab2a1c83df0eb1044b4194724e7259eb#diff-dcfcdaaf69076aa3365199f2060cf328R28

**Comment by Jude95** [comment]
看看我的ImageProvider库。→_→

**Comment by haruue** [comment]
已修复于 54107e16a00ff19db3101a1b566fe906150bf100
感谢朱大的 [ImageProvider](https://github.com/Jude95/ImageProvider.git) ，很好用。
